# Generated by Django 6.1 on 2026-08-07 05:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_facturar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(default='9999999999999', help_text='RUC del negocio (placeholder 9999999999999 mientras no haya RUC real).', max_length=13, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='RUC')),
                ('razon_social', models.CharField(default='EMPRESA DE PRUEBA SRI', max_length=300, verbose_name='Razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, verbose_name='Nombre comercial')),
                ('direccion', models.CharField(default='Quito, Ecuador', max_length=300, verbose_name='Dirección (matriz)')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas (ambiente 1)'), ('2', 'Producción (ambiente 2)')], default='1', help_text='1 = pruebas (celcer), 2 = producción (cel).', max_length=1, verbose_name='Ambiente')),
                ('establecimiento', models.CharField(default='001', max_length=3, verbose_name='Establecimiento')),
                ('punto_emision', models.CharField(default='001', max_length=3, verbose_name='Punto de emisión')),
                ('firma', models.FileField(blank=True, help_text='Archivo .p12 emitido por el SRI (o el generado por `crear_firma_prueba`).', null=True, upload_to='firmas/', verbose_name='Firma electrónica (.p12)')),
                ('clave_firma', models.CharField(blank=True, help_text='Contraseña del archivo .p12.', max_length=100, verbose_name='Clave de la firma')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de facturación',
                'verbose_name_plural': 'Configuración de facturación',
            },
        ),
        migrations.CreateModel(
            name='SecuenciaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('ultimo', models.PositiveIntegerField(default=0, verbose_name='Último secuencial usado')),
            ],
            options={
                'verbose_name': 'Secuencia de factura',
                'verbose_name_plural': 'Secuencias de factura',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso', models.CharField(max_length=49, unique=True, verbose_name='Clave de acceso')),
                ('numero_completo', models.CharField(max_length=17, unique=True, verbose_name='Número (estab-pto-sec)')),
                ('secuencial', models.PositiveIntegerField(db_index=True, verbose_name='Secuencial')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('enviada', 'Enviada (esperando autorización)'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=15, verbose_name='Estado')),
                ('xml_firmado', models.TextField(verbose_name='XML firmado')),
                ('xml_autorizado', models.TextField(blank=True, verbose_name='XML autorizado (SRI)')),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, verbose_name='Número de autorización')),
                ('mensajes', models.TextField(blank=True, verbose_name='Mensajes del SRI')),
                ('intentos', models.PositiveIntegerField(default=0, verbose_name='Intentos de envío')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='LogSri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', max_length=10, verbose_name='Nivel')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='facturacion.comprobante', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Log SRI',
                'verbose_name_plural': 'Logs SRI',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['estado', 'creado'], name='facturacion_estado_0bd59a_idx'),
        ),
    ]
