# Generated by Django 6.1 on 2026-08-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisorconfig',
            name='agente_retencion',
            field=models.BooleanField(default=False, help_text='Marcar solo si el RUC está registrado como agente de retención.', verbose_name='Agente de retención'),
        ),
        migrations.AddField(
            model_name='emisorconfig',
            name='contribuyente_especial',
            field=models.CharField(blank=True, help_text='Dejar vacío si no es contribuyente especial (máx. 13 caracteres).', max_length=13, verbose_name='N.º resolución de contribuyente especial'),
        ),
        migrations.AddField(
            model_name='emisorconfig',
            name='obligado_contabilidad',
            field=models.BooleanField(default=False, help_text='Marcar solo si el RUC está registrado como obligado a llevar contabilidad (personas naturales: NO).', verbose_name='Obligado a llevar contabilidad'),
        ),
    ]
